from typing import Protocol, Optional
from arbscan.models import Quote

class QuoteFeed(Protocol):
    def subscribe(self, symbols: list[str]) -> None: ...
    def get_quote(self, symbol: str) -> Optional[Quote]: ...
    def is_connected(self) -> bool: ...
